#!/bin/sh

lang="$1"

tmp_path="/tmp/com.b1nary.protobuf.bootstrap"
out_dir="proto/${lang}"
tmp_dir="${tmp_path}/${out_dir}"

if [ -e "${tmp_path}" ]; then
	rm -rf "${tmp_path}"
fi

if [ -e "${out_dir}" ]; then
	rm -rf "${out_dir}"
fi

mkdir -p "${tmp_dir}"
rmdir "${tmp_dir}"

cp -r "proto/" "${tmp_dir}/" &&
mv "${tmp_dir}/" "${out_dir}/" &&

cd "${out_dir}" &&
if [ "$lang" = "go" ]; then
	protoc "--${lang}_out=plugins=grpc:." *.proto
else
	protoc "--${lang}_out=." *.proto
fi


rm -rf "${tmp_path}"
